Milestone3
WCanirinka/facebook-clone pull request #5
Opened 2020-01-23 21:07 UTC by 300ms

This pull request has been created for a code review. There is a misunderstanding about omniauth so please ignore changes about omniauth and omniauth-facebook.

2020-01-24 15:33 UTC, mosaaleb requested changes
## Well done Team :clap:

#### we still need to work on few requirements before moving on

- [x] our specs are empty

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)

Let's add model and integration specs for `post` functionality.

- [x] check out my comments below.


#### Please handle these requirements and submit a new code review

##### Muhammad Ebeid

2020-01-24 15:33 UTC, mosaaleb commented on app/controllers/users_controller.rb
> +  def show
- [ ] user controller # index displays all users

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png)

Just implement the user index and ignore the friendship functionality until friendships milestone.

2020-01-24 15:33 UTC, mosaaleb commented on app/models/post.rb
> +  validates :user_id, presence: true
- [ ] `belongs_to :user` adds presence validation to `user_id` by default.
[check this](https://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html)

2020-01-24 15:33 UTC, mosaaleb commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
- [ ] **[OPTIONAL]** devise already takes care of user attributes (email, password), if you checked `config/initializers/devise.rb` file, you will find all email and password configuration and you can edit it there.

2020-01-24 15:33 UTC, mosaaleb commented on app/views/posts/_post.html.erb
> +    <% if @logged_in %>
- [ ] There shoud be absolutely NO logic in views.


![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png)


View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
Rails has built-in mechanism to deal with view-related logic which is View Helpers (app/helpers/*_helper.rb). So the common convention is to move any logic in the views to the helpers. Please take a look at [this](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for more information.

2020-01-24 15:33 UTC, mosaaleb commented on app/views/posts/index.html.erb
> +<% if user_signed_in? %>
- [ ] Please move the view logic to post helper module.

2020-01-24 15:33 UTC, mosaaleb commented on app/views/posts/_post.html.erb
> +        <h6><%= User.find_by(id: post.user_id).first_name %></h6>
- [ ] Why not just `post.user.first_name`, we already have the right association in our models

2020-01-25 02:23 UTC, Ispirett approved these changes
## Status Approved :+1:  :100: 
Great work implementing  the tests ask requested @300ms @WCanirinka 
Please  consider adding more tests for model functionality, like the downcase method for the user and
maximum length for content.

2020-01-27 13:52 UTC, merged